env:
  es6: true
  node: true
  mocha: true

parserOptions:
  ecmaVersion: 2017

plugins:
  - haraka

root: true

rules:
  semi-style: [error, last]
  prefer-template: "warn"
  no-unneeded-ternary: 1

extends: ["eslint:recommended", "plugin:haraka/recommended"]
